site_name: Persona Leaderboard
nav:
  - Home: index.md
  - Basic gpt4o: basic-gpt4o.md
  - Basic gpt4o-mini: basic-gpt4o.md
  - gpt-3.5: basic-gpt3.5.md
theme:
  material
markdown_extensions:
  - pymdownx.blocks.admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
